# ============================================================
# Usage:
#   make up                   → start via Docker Compose (default)
#   make up USE_KIND=true     → provision kind cluster, then deploy
#   make down                 → stop (compose or kind, auto-detected)
#   make up PROFILE=pipeline  → pipeline profile overrides
#
# Environment files (loaded in order, later values win):
#   .env          → non-secret defaults, committed to git
#   .env.local    → secrets & local overrides, git-ignored
#                   auto-generated by `make up` on first run
# ============================================================

USE_KIND     		?= false
SCRIPTS_DIR     := scripts
KIND_CONFIG     := cluster/kind-config.yaml
CLUSTER_NAME    := local-cluster
HELM_COMPONENTS := cluster/helm-components.yaml
PROFILE      		?= * 			# comma-separated list, e.g. PROFILE=db,storage

SHELL           := /bin/bash
.DEFAULT_GOAL   := help

# ── Modular sub-makefiles ────────────────────────────────────
include scripts/make/compose.mk
include scripts/make/query.mk
include scripts/make/mock.mk
include scripts/make/ollama.mk
include scripts/make/proxy.mk
include scripts/make/security.mk

# Export so scripts can inherit without re-reading
export KIND_CLUSTER_NAME := $(CLUSTER_NAME)
export HELM_COMPONENTS_CONFIG := $(CURDIR)/$(HELM_COMPONENTS)

.PHONY: help up down health smoke-test \
        kind-up kind-down kind-status .env \
        secrets rotate

# ── Help ────────────────────────────────────────────────────
default: help
help: ## Show this help
	@echo ""
	@echo "  Usage: make <target> [USE_KIND=true] [PROFILE=<profile>]"
	@echo ""
	@grep -Eh '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}'
	@echo ""
	@echo "  Examples:"
	@echo "    make up                   # Docker Compose (default)"
	@echo "    make up USE_KIND=true     # kind cluster + deploy"
	@echo "    make up PROFILE=pipeline  # pipeline profile overrides"
	@echo ""

# ── Secrets targets ──────────────────────────────────────────
secrets: ## Generate any missing secrets into .env.local
	@bash scripts/gen-secrets.sh

rotate: ## Rotate specific secrets  (KEYS=KEY1,KEY2)
	@[[ -n "$(KEYS)" ]] || { \
	  echo "❌  Usage: make rotate KEYS=KEY1,KEY2"; \
	  echo "   Example: make rotate KEYS=MINIO_ROOT_PASSWORD,AIRFLOW_SECRET_KEY"; \
	  exit 1; \
	}
	@bash scripts/gen-secrets.sh --rotate "$(KEYS)"

.env.local: ## Generate .env.local if it does not exist
	@bash scripts/gen-secrets.sh

# Compatibility alias: `make .env` still works but delegates to .env.local
.env: .env.local

# ── Entry points (branch on USE_KIND) ───────────────────────
ifeq ($(USE_KIND),true)

up: kind-up ## Start stack — kind cluster path (USE_KIND=true)

down: kind-down ## Tear down kind cluster (USE_KIND=true)

else

up: .env compose-up ## Start stack — Docker Compose path (default)

down: compose-down ## Stop Docker Compose stack

endif

# ── Kind cluster targets ─────────────────────────────────────
kind-up: ## (internal) Provision kind cluster and deploy stack
	@bash scripts/kind-deploy.sh up $(CLUSTER_NAME) $(KIND_CONFIG)

kind-down: ## (internal) Delete kind cluster
	@bash scripts/kind-deploy.sh down $(CLUSTER_NAME)

kind-status: ## Show kind cluster and pod status
	@bash scripts/kind-deploy.sh status $(CLUSTER_NAME)

# ── Health & smoke ───────────────────────────────────────────
health: ## Check health of all running services
	@bash scripts/health-check.sh


# =============================================================================
##@ Setup
# =============================================================================

.PHONY: check-deps
check-deps: ## Check required tools (add --install to auto-install)
	@bash $(SCRIPTS_DIR)/check-deps.sh $(ARGS)

.PHONY: helm-repos
helm-repos: ## Add and update Helm repos for all enabled components
	@bash $(SCRIPTS_DIR)/kube-helm-repos.sh

# =============================================================================
##@ Kubernetes — Validation
# =============================================================================

.PHONY: kube-validate
kube-validate: ## Validate helm-components.yaml: fields, file refs, dep cycles
	@bash $(SCRIPTS_DIR)/kube-validate.sh

.PHONY: kube-validate-render
kube-validate-render: helm-repos ## Validate + helm template dry-run (no cluster needed)
	@bash $(SCRIPTS_DIR)/kube-validate.sh --render

# =============================================================================
##@ Kubernetes — Cluster
# =============================================================================

.PHONY: kube-start
kube-start: check-deps ## Create the local Kind cluster
	@if kind get clusters 2>/dev/null | grep -qx "$(CLUSTER_NAME)"; then \
	  echo "  ℹ Cluster '$(CLUSTER_NAME)' already running"; \
	else \
	  echo "  Creating cluster '$(CLUSTER_NAME)'..."; \
	  kind create cluster --name $(CLUSTER_NAME) --config $(KIND_CONFIG); \
	fi

.PHONY: kube-stop
kube-stop: ## Delete the Kind cluster (destroys all workloads)
	kind delete cluster --name $(CLUSTER_NAME)

# =============================================================================
##@ Kubernetes — Helm Components
# =============================================================================

.PHONY: kube-secrets
kube-secrets: .env.local kube-start ## Create Kubernetes Secrets in db and airflow namespaces from .env.local
	@bash $(SCRIPTS_DIR)/kube-secrets.sh

.PHONY: kube-deploy
kube-deploy: kube-start helm-repos kube-secrets ## Deploy all enabled components (dependency-ordered)
	@bash $(SCRIPTS_DIR)/kube-deploy.sh

.PHONY: kube-deploy-one
kube-deploy-one: kube-start helm-repos kube-secrets ## Deploy a single component  (COMPONENT=postgres)
	@[[ -n "$(COMPONENT)" ]] || { echo "Usage: make kube-deploy-one COMPONENT=<n>"; exit 1; }
	@bash $(SCRIPTS_DIR)/kube-deploy.sh $(COMPONENT)

.PHONY: kube-remove
kube-remove: ## Remove all enabled Helm releases (cluster kept)
	@bash $(SCRIPTS_DIR)/kube-remove.sh

.PHONY: kube-remove-one
kube-remove-one: ## Remove a single Helm release  (COMPONENT=airflow)
	@[[ -n "$(COMPONENT)" ]] || { echo "Usage: make kube-remove-one COMPONENT=<n>"; exit 1; }
	@bash $(SCRIPTS_DIR)/kube-remove.sh $(COMPONENT)

# =============================================================================
##@ Kubernetes — Lifecycle Shortcuts
# =============================================================================

.PHONY: kube-up
kube-up: kube-deploy ## Full bring-up: cluster + all enabled components
	@echo ""
	@echo "  🎉 Kube stack ready — run: make kube-port-forward"

.PHONY: kube-down
kube-down: kube-remove kube-stop ## Tear down releases then delete the cluster

# =============================================================================
##@ Kubernetes — Operations
# =============================================================================

.PHONY: kube-status
kube-status: ## Show cluster, release, pod, and port-forward status
	@bash $(SCRIPTS_DIR)/kube-status.sh

.PHONY: kube-health
kube-health: ## Poll pod readiness for all (or one) component(s)  (COMPONENT=name, KUBE_HEALTH_TIMEOUT=300)
	@bash $(SCRIPTS_DIR)/kube-health.sh $(COMPONENT)

.PHONY: kube-logs
kube-logs: ## Show pod logs for a component  (COMPONENT=name, optional: FLAG=--follow|--previous)
	@[[ -n "$(COMPONENT)" ]] || { echo "Usage: make kube-logs COMPONENT=<name>"; exit 1; }
	@bash $(SCRIPTS_DIR)/kube-status.sh logs $(COMPONENT) $(FLAG)

.PHONY: kube-port-forward
kube-port-forward: ## Start background port-forwards for all enabled components
	@bash $(SCRIPTS_DIR)/kube-port-forward.sh

.PHONY: kube-port-forward-stop
kube-port-forward-stop: ## Kill all active kubectl port-forward processes
	@bash $(SCRIPTS_DIR)/kube-port-forward.sh stop

.PHONY: kube-port-forward-status
kube-port-forward-status: ## List running port-forward processes
	@bash $(SCRIPTS_DIR)/kube-port-forward.sh status

.PHONY: kube-stubs-reload
kube-stubs-reload: ## Rebuild wiremock-stubs ConfigMap from compose/wiremock/mappings/ and restart WireMock pod
	@bash $(SCRIPTS_DIR)/kube-secrets.sh
	@kubectl rollout restart deployment/wiremock -n misc
	@echo "  ↻ WireMock restarting with updated stubs"
