# ============================================================
# Usage:
#   make up                   → start via Docker Compose (default)
#   make up USE_KIND=true     → provision kind cluster, then deploy
#   make down                 → stop (compose or kind, auto-detected)
#   make up PROFILE=pipeline  → pipeline profile overrides
#
# Environment files (loaded in order, later values win):
#   .env          → non-secret defaults, committed to git
#   .env.local    → secrets & local overrides, git-ignored
#                   auto-generated by `make up` on first run
# ============================================================

ENV          ?= dev
USE_KIND     ?= false
CLUSTER_NAME ?= local-cluster
KIND_CONFIG  ?= ../cluster/kind-config.yaml
PROFILE      ?=  			# comma-separated list, e.g. PROFILE=db,storage

# ── Env files ────────────────────────────────────────────────
# .env holds non-secret defaults; .env.local holds secrets and
# local overrides. Both are passed to every docker compose call.
# .env.local values take precedence (it is listed second).
ENV_FILE_FLAGS := --env-file .env $(if $(wildcard .env.local),--env-file .env.local)

# ── Compose setup ───────────────────────────────────────────

# Gather all docker-compose files in ./compose; base file first.
COMPOSE_GLOB     := $(wildcard ./compose/docker-compose*.yaml)
COMPOSE_FILE_LIST := $(COMPOSE_GLOB)

# Build profile flags for `docker compose`
PROFILES      := $(strip $(shell echo $(PROFILE) | tr ',' ' '))
PROFILE_FLAGS := $(shell for p in $(PROFILES); do if [ -n "$$p" ]; then printf -- '--profile %s ' "$$p"; fi; done)

# Master compose command — env files + profiles + compose files
DC := docker compose $(ENV_FILE_FLAGS) $(PROFILE_FLAGS) \
      $(foreach f,$(COMPOSE_FILE_LIST),-f $(f))

.PHONY: help up down build restart logs shell ps clean prune lint health smoke-test \
        kind-up kind-down kind-status compose-up compose-down .env

# ── Help ────────────────────────────────────────────────────
default: help
help: ## Show this help
	@echo ""
	@echo "  Usage: make <target> [USE_KIND=true] [ENV=dev|prod|ci]"
	@echo ""
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}'
	@echo ""
	@echo "  Examples:"
	@echo "    make up                   # Docker Compose (default)"
	@echo "    make up USE_KIND=true     # kind cluster + deploy"
	@echo "    make up PROFILE=pipeline  # pipeline profile overrides"
	@echo ""

# ── Explicit secrets target (re-run gen at any time) ────────
secrets: ## Generate missing secrets into .env.local
	@bash scripts/gen-secrets.sh

# ── .env bootstrap ────────────────────────────────────
# .env.local holds secrets and local overrides (git-ignored).
# The script is idempotent: it only writes keys that are absent.
.env: 
	@bash scripts/gen-secrets.sh

# ── Entry points (branch on USE_KIND) ───────────────────────
ifeq ($(USE_KIND),true)

up: kind-up ## Start stack — kind cluster path (USE_KIND=true)

down: kind-down ## Tear down kind cluster (USE_KIND=true)

else

up: .env compose-up ## Start stack — Docker Compose path (default)

down: compose-down ## Stop Docker Compose stack

endif


# ── Docker Compose targets ───────────────────────────────────
compose-up: .env # (internal) Start via Docker Compose
	@echo "🐳 Starting analytics stack via Docker Compose [ENV=$(ENV)]..."
	$(DC) up -d --remove-orphans
	@echo ""
	@echo "🚀 Stack is up:"
	@echo "   Trino UI          → http://localhost:$${TRINO_PORT:-8080}"
	@echo "   Iceberg REST      → http://localhost:$${ICEBERG_REST_PORT:-8181}"
	@echo "   MinIO Console     → http://localhost:$${MINIO_CONSOLE_PORT:-9001}"
	@echo "   Postgres          → localhost:5432 (dev only)"
	@echo ""

compose-down: ## (internal) Stop Docker Compose stack
	$(DC) down

build: ## Pull latest images
	$(DC) pull

restart: ## Restart all Compose services
	$(DC) restart

logs: ## Tail logs — make logs SERVICE=trino
	$(DC) logs -f $(SERVICE)

shell: ## Shell into a service — make shell SERVICE=trino
	$(DC) exec $(SERVICE) bash || $(DC) exec $(SERVICE) sh

ps: ## Show running containers and health status
	$(DC) ps

clean: ## Remove containers, networks, volumes — ⚠️  destroys data
	$(DC) down -v --remove-orphans

prune: ## Remove ALL unused Docker resources — ⚠️  dangerous
	docker system prune -af --volumes

lint: ## Validate compose config syntax
	$(DC) config --quiet && echo "✅ Compose config is valid"

sync: ## Perform git submodule sync
	git submodule update --remote dags

# ── Application Specific Commands ────────────────────────────
dagcheck: ## Airflow Dags Check Custom Command
	@echo "Checking DAGs for errors..."
	$(DC) exec -w /opt/airflow airflow-scheduler python3 scripts/infra/check_dags.py

# ── Kind cluster targets ─────────────────────────────────────
kind-up: # (internal) Provision kind cluster and deploy stack
	@bash scripts/kind-deploy.sh up $(CLUSTER_NAME) $(KIND_CONFIG)

kind-down: # (internal) Delete kind cluster
	@bash scripts/kind-deploy.sh down $(CLUSTER_NAME)

kind-status: ## Show kind cluster and pod status
	@bash scripts/kind-deploy.sh status $(CLUSTER_NAME)

# ── Health & smoke ───────────────────────────────────────────
health: ## Check health of all running services
	@bash scripts/health-check.sh


