# ============================================================
# Usage:
#   make up                   → start via Docker Compose (default)
#   make up USE_KIND=true     → provision kind cluster, then deploy
#   make down                 → stop (compose or kind, auto-detected)
#   make up PROFILE=pipeline  → pipeline profile overrides
#
# Environment files (loaded in order, later values win):
#   .env          → non-secret defaults, committed to git
#   .env.local    → secrets & local overrides, git-ignored
#                   auto-generated by `make up` on first run
# ============================================================

USE_KIND     		?= false
SCRIPTS_DIR     := scripts
KIND_CONFIG     := cluster/kind-config.yaml
CLUSTER_NAME    := local-cluster
HELM_COMPONENTS := cluster/helm-components.yaml
PROFILE      		?= * 			# comma-separated list, e.g. PROFILE=db,storage

SHELL           := /bin/bash
.DEFAULT_GOAL   := help

# ── Modular sub-makefiles ────────────────────────────────────
include scripts/make/query.mk
include scripts/make/mock.mk
include scripts/make/ollama.mk
include scripts/make/proxy.mk
include scripts/make/security.mk

# ── Read ICEBERG_REST_VERSION from .env (no -include, avoids .env remake loop) ─
ICEBERG_REST_VERSION := $(strip $(shell grep -s '^ICEBERG_REST_VERSION=' .env | cut -d= -f2))
ICEBERG_REST_VERSION := $(if $(ICEBERG_REST_VERSION),$(ICEBERG_REST_VERSION),0.10.0)

# Export so scripts can inherit without re-reading
export KIND_CLUSTER_NAME := $(CLUSTER_NAME)
export HELM_COMPONENTS_CONFIG := $(CURDIR)/$(HELM_COMPONENTS)

# ── Env files ────────────────────────────────────────────────
# .env holds non-secret defaults; .env.local holds secrets and
# local overrides. Both are passed to every docker compose call.
# .env.local values take precedence (it is listed second).
ENV_FILE_FLAGS := --env-file .env $(if $(wildcard .env.local),--env-file .env.local)

# ── Compose setup ───────────────────────────────────────────

# Gather all docker-compose files in ./compose; base file first.
COMPOSE_GLOB     := $(wildcard ./compose/docker-compose*.yaml)
COMPOSE_FILE_LIST := $(COMPOSE_GLOB)

# Build profile flags for `docker compose`
PROFILES      := $(strip $(shell echo "$(PROFILE)" | tr ',' ' '))
PROFILE_FLAGS := $(strip $(foreach p,$(PROFILES),$(if $(p),--profile "$(p)")))

# Master compose command — env files + profiles + compose files
DC := docker compose $(ENV_FILE_FLAGS) $(PROFILE_FLAGS) \
      $(foreach f,$(COMPOSE_FILE_LIST),-f $(f))

.PHONY: help up down build restart logs shell ps clean prune lint health smoke-test \
        kind-up kind-down kind-status compose-up compose-down .env airflow-dirs \
        secrets rotate sync dagcheck build-query query pipeline

# ── Help ────────────────────────────────────────────────────
default: help
help: ## Show this help
	@echo ""
	@echo "  Usage: make <target> [USE_KIND=true] [PROFILE=<profile>]"
	@echo ""
	@grep -Eh '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}'
	@echo ""
	@echo "  Examples:"
	@echo "    make up                   # Docker Compose (default)"
	@echo "    make up USE_KIND=true     # kind cluster + deploy"
	@echo "    make up PROFILE=pipeline  # pipeline profile overrides"
	@echo ""

# ── Explicit secrets target (re-run gen at any time) ────────
secrets: ## Generate any missing secrets into .env.local
	@bash scripts/gen-secrets.sh
 
# CHANGE [5]: Rotation target. Passes --rotate to gen-secrets.sh which
# forwards it to gen_secrets.py. Only the named KEYS are removed and
# regenerated; all other secrets remain untouched.
rotate: ## Rotate specific secrets  (KEYS=KEY1,KEY2)
	@[[ -n "$(KEYS)" ]] || { \
	  echo "❌  Usage: make rotate KEYS=KEY1,KEY2"; \
	  echo "   Example: make rotate KEYS=MINIO_ROOT_PASSWORD,AIRFLOW_SECRET_KEY"; \
	  exit 1; \
	}
	@bash scripts/gen-secrets.sh --rotate "$(KEYS)"

# ── Secrets targets ──────────────────────────────────────────
# CHANGE [4]: Renamed the Make prerequisite from `.env` to `.env.local`
# so Make tracks the correct output file.
#
# The original `.env` target was semantically wrong: `.env` is a
# committed file that always exists, so Make considered the rule
# up-to-date on first checkout and never ran gen-secrets.sh for new
# team members who lacked .env.local.
#
# `.env.local` as the target name fixes this — when the file is absent
# (fresh clone, clean CI runner), Make correctly treats it as missing
# and runs the recipe.
 
.env.local: ## Generate .env.local if it does not exist
	@bash scripts/gen-secrets.sh
 
# Compatibility alias: `make .env` still works but delegates to .env.local
.env: .env.local

# ── Entry points (branch on USE_KIND) ───────────────────────
ifeq ($(USE_KIND),true)

up: kind-up ## Start stack — kind cluster path (USE_KIND=true)

down: kind-down ## Tear down kind cluster (USE_KIND=true)

else

up: .env compose-up ## Start stack — Docker Compose path (default)

down: compose-down ## Stop Docker Compose stack

endif


# ── Docker Compose targets ───────────────────────────────────
compose-up: .env # (internal) Start via Docker Compose
	@echo "🐳 Starting your application(s) via Docker Compose [PROFILE=$(PROFILE)]..."
	$(DC) up -d --remove-orphans
	@echo ""
	@echo "🚀 Stack is up"

compose-down: ## (internal) Stop Docker Compose stack
	$(DC) down

build: ## Pull latest images
	$(DC) pull

restart: .env ## Restart all Compose services
	$(DC) down
	$(DC) up -d --remove-orphans
	@echo ""
	@echo "🚀 Stack is restarted"

logs: ## Tail logs — make logs SERVICE=trino
	$(DC) logs -f $(SERVICE)

shell: ## Shell into a service — make shell SERVICE=trino
	$(DC) exec $(SERVICE) bash || $(DC) exec $(SERVICE) sh

ps: ## Show running containers and health status
	$(DC) ps

clean: ## Remove containers, networks, volumes — ⚠️  destroys data
	$(DC) down -v --remove-orphans

prune: ## Remove ALL unused Docker resources — ⚠️  dangerous
	docker system prune -af --volumes

lint: ## Validate compose config syntax
	$(DC) config --quiet && echo "✅ Compose config is valid"

sync: ## Perform git submodule sync
	git submodule update --remote

# ── Application Specific Commands ────────────────────────────
dagcheck: ## Airflow Dags Check Custom Command
	@echo "Checking DAGs for errors..."
	$(DC) exec -w /opt/airflow airflow-scheduler python3 scripts/infra/check_dags.py

build-query: ## Build custom iceberg-rest image (skips if already present)
	@if docker image inspect iceberg-rest-local:$(ICEBERG_REST_VERSION) \
	        >/dev/null 2>&1; then \
	  echo "✅ iceberg-rest-local:$(ICEBERG_REST_VERSION) already exists — skipping build."; \
	else \
	  echo "🔨 Building iceberg-rest-local:$(ICEBERG_REST_VERSION)..."; \
	  docker build \
	    --build-arg ICEBERG_REST_VERSION=$(ICEBERG_REST_VERSION) \
	    --tag iceberg-rest-local:$(ICEBERG_REST_VERSION) \
	    compose/iceberg-rest/; \
	  echo "✅ iceberg-rest-local:$(ICEBERG_REST_VERSION) built"; \
	fi

query: .env build-query ## Start query engine stack (Trino + Iceberg REST + Postgres + MinIO)
	@echo "🔍 Starting query engine stack..."
	docker compose $(ENV_FILE_FLAGS) \
		--profile query --profile db --profile storage \
		$(foreach f,$(COMPOSE_FILE_LIST),-f $(f)) \
		up -d --remove-orphans 
	@echo ""
	@echo "🚀 Query stack is up:"
	@echo "   Trino UI      → http://localhost:$${TRINO_PORT:-8080}"
	@echo "   Iceberg REST  → http://localhost:$${ICEBERG_REST_PORT:-8181}"
	@echo "   MinIO Console → http://localhost:$${MINIO_CONSOLE_PORT:-9001}"
	@echo "   Postgres      → localhost:$${POSTGRES_PORT:-5432} (dev only)"
	@echo ""


airflow-dirs: ## Create Airflow log/plugin dirs with correct permissions (UID 50000 / GID 0)
	@mkdir -p compose/container/logs/airflow compose/container/plugins/airflow
	@chmod 777 compose/container/logs/airflow compose/container/plugins/airflow

pipeline: .env airflow-dirs ## Start pipeline stack (Airflow + Postgres)
	@echo "🔍 Starting pipeline stack..."
	docker compose $(ENV_FILE_FLAGS) \
		--profile pipeline \
		$(foreach f,$(COMPOSE_FILE_LIST),-f $(f)) \
		up -d --remove-orphans 
	@echo ""
	@echo "🚀 Pipeline stack is up:"
	@echo "   Airflow UI    → http://localhost:$${AIRFLOW_API_SERVER_PORT:-8081}"
	@echo "   Postgres      → localhost:$${POSTGRES_PORT:-5432} (dev only)"
	@echo ""

# ── Kind cluster targets ─────────────────────────────────────
kind-up: # (internal) Provision kind cluster and deploy stack
	@bash scripts/kind-deploy.sh up $(CLUSTER_NAME) $(KIND_CONFIG)

kind-down: # (internal) Delete kind cluster
	@bash scripts/kind-deploy.sh down $(CLUSTER_NAME)

kind-status: ## Show kind cluster and pod status
	@bash scripts/kind-deploy.sh status $(CLUSTER_NAME)

# ── Health & smoke ───────────────────────────────────────────
health: ## Check health of all running services
	@bash scripts/health-check.sh


# =============================================================================
##@ Setup
# =============================================================================

.PHONY: check-deps
check-deps: ## Check required tools (add --install to auto-install)
	@bash $(SCRIPTS_DIR)/check-deps.sh $(ARGS)

.PHONY: helm-repos
helm-repos: ## Add and update Helm repos for all enabled components
	@bash $(SCRIPTS_DIR)/kube-helm-repos.sh

# =============================================================================
##@ Kubernetes — Cluster
# =============================================================================

# =============================================================================
##@ Kubernetes — Validation
# =============================================================================

.PHONY: kube-validate
kube-validate: ## Validate helm-components.yaml: fields, file refs, dep cycles
	@bash $(SCRIPTS_DIR)/kube-validate.sh

.PHONY: kube-validate-render
kube-validate-render: helm-repos ## Validate + helm template dry-run (no cluster needed)
	@bash $(SCRIPTS_DIR)/kube-validate.sh --render

# =============================================================================
##@ Kubernetes — Cluster
# =============================================================================

.PHONY: kube-start
kube-start: check-deps ## Create the local Kind cluster
	@if kind get clusters 2>/dev/null | grep -qx "$(CLUSTER_NAME)"; then \
	  echo "  ℹ Cluster '$(CLUSTER_NAME)' already running"; \
	else \
	  echo "  Creating cluster '$(CLUSTER_NAME)'..."; \
	  kind create cluster --name $(CLUSTER_NAME) --config $(KIND_CONFIG); \
	fi

.PHONY: kube-stop
kube-stop: ## Delete the Kind cluster (destroys all workloads)
	kind delete cluster --name $(CLUSTER_NAME)

# =============================================================================
##@ Kubernetes — Helm Components
# =============================================================================

.PHONY: kube-secrets
kube-secrets: .env.local kube-start ## Create Kubernetes Secrets in db and airflow namespaces from .env.local
	@bash $(SCRIPTS_DIR)/kube-secrets.sh

.PHONY: kube-deploy
kube-deploy: kube-start helm-repos kube-secrets ## Deploy all enabled components (dependency-ordered)
	@bash $(SCRIPTS_DIR)/kube-deploy.sh

.PHONY: kube-deploy-one
kube-deploy-one: kube-start helm-repos kube-secrets ## Deploy a single component  (COMPONENT=postgres)
	@[[ -n "$(COMPONENT)" ]] || { echo "Usage: make kube-deploy-one COMPONENT=<n>"; exit 1; }
	@bash $(SCRIPTS_DIR)/kube-deploy.sh $(COMPONENT)

.PHONY: kube-remove
kube-remove: ## Remove all enabled Helm releases (cluster kept)
	@bash $(SCRIPTS_DIR)/kube-remove.sh

.PHONY: kube-remove-one
kube-remove-one: ## Remove a single Helm release  (COMPONENT=airflow)
	@[[ -n "$(COMPONENT)" ]] || { echo "Usage: make kube-remove-one COMPONENT=<n>"; exit 1; }
	@bash $(SCRIPTS_DIR)/kube-remove.sh $(COMPONENT)

# =============================================================================
##@ Kubernetes — Lifecycle Shortcuts
# =============================================================================

.PHONY: kube-up
kube-up: kube-deploy ## Full bring-up: cluster + all enabled components
	@echo ""
	@echo "  🎉 Kube stack ready — run: make kube-port-forward"

.PHONY: kube-down
kube-down: kube-remove kube-stop ## Tear down releases then delete the cluster

# =============================================================================
##@ Kubernetes — Operations
# =============================================================================

.PHONY: kube-status
kube-status: ## Show cluster, release, pod, and port-forward status
	@bash $(SCRIPTS_DIR)/kube-status.sh

.PHONY: kube-port-forward
kube-port-forward: ## Start background port-forwards for all enabled components
	@bash $(SCRIPTS_DIR)/kube-port-forward.sh

.PHONY: kube-port-forward-stop
kube-port-forward-stop: ## Kill all active kubectl port-forward processes
	@bash $(SCRIPTS_DIR)/kube-port-forward.sh stop

.PHONY: kube-port-forward-status
kube-port-forward-status: ## List running port-forward processes
	@bash $(SCRIPTS_DIR)/kube-port-forward.sh status

.PHONY: kube-stubs-reload
kube-stubs-reload: ## Rebuild wiremock-stubs ConfigMap from compose/wiremock/mappings/ and restart WireMock pod
	@bash $(SCRIPTS_DIR)/kube-secrets.sh
	@kubectl rollout restart deployment/wiremock -n misc
	@echo "  ↻ WireMock restarting with updated stubs"