#!/usr/bin/env bash
# ============================================================
# scripts/gen-secrets.sh
#
# Generates secrets into .env.local for any key that is not
# already defined there. Safe to re-run — existing values are
# never overwritten.
#
# Called automatically by `make up` via the .env.local target.
# ============================================================
set -euo pipefail

ENV_LOCAL=".env.local"

# ── Helpers ──────────────────────────────────────────────────

# Returns 0 (true) if the key already exists and is non-empty in .env.local
key_exists() {
  local key="$1"
  [ -f "$ENV_LOCAL" ] && grep -qE "^${key}=.+" "$ENV_LOCAL"
}

# Appends KEY=VALUE to .env.local
write_key() {
  local key="$1"
  local value="$2"
  echo "${key}=${value}" >> "$ENV_LOCAL"
  echo "  ✔  ${key}"
}

# Generates a URL-safe random string of <n> bytes (base64-encoded, no padding)
rand_b64() {
  local n="${1:-32}"
  openssl rand -base64 "$n" | tr -d '/+=' | head -c "$n"
}

# Generates an Airflow Fernet key (must be 32-byte, url-safe base64)
fernet_key() {
  python3 - <<'EOF'
try:
    from cryptography.fernet import Fernet
    print(Fernet.generate_key().decode())
except ImportError:
    import base64, os
    print(base64.urlsafe_b64encode(os.urandom(32)).decode())
EOF
}

# ── Bootstrap file ───────────────────────────────────────────
if [ ! -f "$ENV_LOCAL" ]; then
  cat > "$ENV_LOCAL" <<'HEADER'
# .env.local — LOCAL SECRETS & OVERRIDES
# Auto-generated by `make up` via scripts/gen-secrets.sh.
# ⚠️  Never commit this file. It is listed in .gitignore.
HEADER
  echo ""
  echo "📄 Created ${ENV_LOCAL}"
fi

echo "🔐 Checking secrets in ${ENV_LOCAL}..."
echo ""

CHANGED=false

# ── MinIO ────────────────────────────────────────────────────
if ! key_exists "MINIO_ROOT_USER"; then
  write_key "MINIO_ROOT_USER" "minioadmin"
  CHANGED=true
fi

if ! key_exists "MINIO_ROOT_PASSWORD"; then
  write_key "MINIO_ROOT_PASSWORD" "$(rand_b64 24)"
  CHANGED=true
fi

# ── Postgres ─────────────────────────────────────────────────
if ! key_exists "POSTGRES_USER"; then
  write_key "POSTGRES_USER" "airflow"
  CHANGED=true
fi

if ! key_exists "POSTGRES_PASSWORD"; then
  write_key "POSTGRES_PASSWORD" "$(rand_b64 24)"
  CHANGED=true
fi

if ! key_exists "POSTGRES_DB"; then
  write_key "POSTGRES_DB" "airflow"
  CHANGED=true
fi

# ── Airflow ──────────────────────────────────────────────────
if ! key_exists "AIRFLOW_FERNET_KEY"; then
  write_key "AIRFLOW_FERNET_KEY" "$(fernet_key)"
  CHANGED=true
fi

if ! key_exists "AIRFLOW_SECRET_KEY"; then
  write_key "AIRFLOW_SECRET_KEY" "$(rand_b64 32)"
  CHANGED=true
fi

if ! key_exists "AIRFLOW_ADMIN_USER"; then
  write_key "AIRFLOW_ADMIN_USER" "admin"
  CHANGED=true
fi

if ! key_exists "AIRFLOW_ADMIN_PASSWORD"; then
  write_key "AIRFLOW_ADMIN_PASSWORD" "$(rand_b64 16)"
  CHANGED=true
fi

if ! key_exists "AIRFLOW_ADMIN_EMAIL"; then
  write_key "AIRFLOW_ADMIN_EMAIL" "admin@example.com"
  CHANGED=true
fi

# ── Summary ──────────────────────────────────────────────────
echo ""
if [ "$CHANGED" = true ]; then
  echo "✅ Secrets written to ${ENV_LOCAL}"
  echo "   Review the file before sharing or deploying:"
  echo "   cat ${ENV_LOCAL}"
else
  echo "✅ All secrets already present in ${ENV_LOCAL} — nothing changed."
fi
echo ""