#!/usr/bin/env python3
"""
scripts/gen_secrets.py

Reads config/secrets.yaml, validates every entry against a strict
schema, then appends any missing secrets to .env.local.

Existing keys are never overwritten — safe to re-run at any time.
Pass --rotate KEY1,KEY2 to forcibly regenerate specific keys.

Invoked by scripts/gen-secrets.sh, but can also be run directly:
    python3 scripts/gen_secrets.py --config config/secrets.yaml \\
                                   --env-file .env.local
"""
from __future__ import annotations

import argparse
import datetime
import math
import os
import re
import secrets as _secrets
import socket
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    print("❌  PyYAML is not installed. Run: pip3 install pyyaml", file=sys.stderr)
    sys.exit(1)


# ── Constants ────────────────────────────────────────────────────────────────

VALID_METHODS  = frozenset({"static", "random_base64", "random_hex", "fernet"})
ALLOWED_FIELDS = frozenset({"key", "method", "value", "length"})

# CHANGE [7]: Version gate — bump when schema gains new fields/methods.
SUPPORTED_VERSIONS = frozenset({"1"})

KEY_RE = re.compile(r"^[A-Z][A-Z0-9_]+$")

# CHANGE [1]: Keys whose names match this pattern must never use method=static.
# Prevents plaintext secrets being quietly committed to VCS via secrets.yaml.
SENSITIVE_KEY_RE = re.compile(
    r"(PASSWORD|SECRET|KEY|TOKEN|CREDENTIAL|FERNET)", re.IGNORECASE
)

ENV_VAR_RE = re.compile(r"^([A-Z][A-Z0-9_]+)=")

LENGTH_MIN     = 8
LENGTH_MAX     = 256
LENGTH_DEFAULT = 32

ENV_LOCAL_HEADER = (
    "# .env.local — LOCAL SECRETS & OVERRIDES\n"
    "# Auto-generated by `make up` via scripts/gen-secrets.sh.\n"
    "# ⚠️  Never commit this file. It is listed in .gitignore.\n"
)


# ── Exceptions ───────────────────────────────────────────────────────────────

# CHANGE [11]: Replaced ad-hoc _die() + sys.exit() pattern with a typed
# exception. Benefits:
#   - Testable: unit tests can catch ConfigError instead of patching sys.exit
#   - Consistent: all fatal errors flow through one path
#   - Still exits 1 via SystemExit base class
class ConfigError(SystemExit):
    """Raised for user-facing configuration errors. Exits with code 1."""

    def __init__(self, msg: str) -> None:
        print(f"❌  {msg}", file=sys.stderr)
        super().__init__(1)


# ── Validation ───────────────────────────────────────────────────────────────

def validate(config: Any, config_path: str) -> list[dict]:
    """
    Validate the full YAML structure.

    Collects every error across all entries before raising so the user
    sees the complete list in one run rather than fixing one at a time.

    Returns the validated list of secret definitions on success.
    Raises ConfigError with a formatted report on failure.
    """
    errors: list[str] = []

    # ── Top-level structure ───────────────────────────────────────────────────
    if not isinstance(config, dict):
        raise ConfigError(
            f"{config_path}: root must be a YAML mapping, "
            f"got {type(config).__name__!r}"
        )

    # CHANGE [7]: Validate schema version before processing anything else.
    version = config.get("version")
    if not version:
        raise ConfigError(
            f"{config_path}: missing required top-level field 'version'.\n"
            f"   Add:  version: \"1\""
        )
    if str(version) not in SUPPORTED_VERSIONS:
        raise ConfigError(
            f"{config_path}: unsupported schema version {version!r}.\n"
            f"   Supported: {', '.join(sorted(SUPPORTED_VERSIONS))}"
        )

    if "secrets" not in config:
        raise ConfigError(
            f"{config_path}: missing required top-level key 'secrets'"
        )

    secrets = config["secrets"]

    if not isinstance(secrets, list):
        raise ConfigError(
            f"{config_path}: 'secrets' must be a list, "
            f"got {type(secrets).__name__!r}"
        )

    if not secrets:
        raise ConfigError(
            f"{config_path}: 'secrets' list is empty — nothing to generate"
        )

    # ── Per-entry ─────────────────────────────────────────────────────────────
    seen: dict[str, int] = {}

    for idx, entry in enumerate(secrets):
        loc = f"{config_path}: secrets[{idx}]"

        if not isinstance(entry, dict):
            errors.append(
                f"{loc}: each entry must be a YAML mapping, "
                f"got {type(entry).__name__!r}"
            )
            continue

        unknown = sorted(set(entry) - ALLOWED_FIELDS)
        if unknown:
            errors.append(
                f"{loc}: unknown field(s): {', '.join(unknown)}  "
                f"(allowed: {', '.join(sorted(ALLOWED_FIELDS))})"
            )

        # ── key ───────────────────────────────────────────────────────────────
        key: str = entry.get("key", "")
        label = key or f"<entry {idx}>"

        if not key:
            errors.append(f"{loc}: missing required field 'key'")
        elif not isinstance(key, str):
            errors.append(
                f"{loc}: 'key' must be a string, got {type(key).__name__!r}"
            )
            label = f"<entry {idx}>"
        elif not KEY_RE.match(key):
            errors.append(
                f"{loc}: 'key' {key!r} is not a valid env var name "
                f"(must match ^[A-Z][A-Z0-9_]+$)"
            )

        if key:
            if key in seen:
                errors.append(
                    f"{loc}: duplicate key {key!r} "
                    f"(first defined at secrets[{seen[key]}])"
                )
            else:
                seen[key] = idx

        # ── method ────────────────────────────────────────────────────────────
        method: str = entry.get("method", "")

        if not method:
            errors.append(f"{loc} ({label}): missing required field 'method'")
            continue

        if not isinstance(method, str):
            errors.append(
                f"{loc} ({label}): 'method' must be a string, "
                f"got {type(method).__name__!r}"
            )
            continue

        if method not in VALID_METHODS:
            errors.append(
                f"{loc} ({label}): unknown method {method!r}  "
                f"(valid: {', '.join(sorted(VALID_METHODS))})"
            )
            continue

        has_value  = "value"  in entry
        has_length = "length" in entry
        value      = entry.get("value")
        length     = entry.get("length")

        # ── static ────────────────────────────────────────────────────────────
        if method == "static":
            if not has_value:
                errors.append(
                    f"{loc} ({label}): method 'static' requires a 'value' field"
                )
            elif not isinstance(value, (str, int, float, bool)):
                errors.append(
                    f"{loc} ({label}): 'value' must be a scalar "
                    f"(string / number / bool), got {type(value).__name__!r}"
                )
            elif str(value).strip() == "":
                errors.append(
                    f"{loc} ({label}): 'value' must not be empty for method 'static'"
                )

            if has_length:
                errors.append(
                    f"{loc} ({label}): 'length' is not allowed for method 'static'"
                )

            # CHANGE [1]: Block method=static on sensitive key names.
            # Prevents plaintext passwords/tokens being committed via secrets.yaml.
            if key and SENSITIVE_KEY_RE.search(key):
                errors.append(
                    f"{loc} ({label}): key {key!r} looks sensitive — "
                    f"method 'static' is not allowed for keys whose names contain "
                    f"PASSWORD, SECRET, KEY, TOKEN, CREDENTIAL, or FERNET. "
                    f"Use 'random_base64', 'random_hex', or 'fernet' instead."
                )

        # ── random_base64 / random_hex ────────────────────────────────────────
        elif method in ("random_base64", "random_hex"):
            if has_value:
                errors.append(
                    f"{loc} ({label}): 'value' is not allowed for method {method!r}"
                )
            if has_length:
                if not isinstance(length, int) or isinstance(length, bool):
                    errors.append(
                        f"{loc} ({label}): 'length' must be an integer, "
                        f"got {type(length).__name__!r}"
                    )
                elif not (LENGTH_MIN <= length <= LENGTH_MAX):
                    errors.append(
                        f"{loc} ({label}): 'length' must be between "
                        f"{LENGTH_MIN} and {LENGTH_MAX}, got {length}"
                    )

        # ── fernet ────────────────────────────────────────────────────────────
        elif method == "fernet":
            if has_value:
                errors.append(
                    f"{loc} ({label}): 'value' is not allowed for method 'fernet'"
                )
            if has_length:
                errors.append(
                    f"{loc} ({label}): 'length' is not allowed for method 'fernet' "
                    "(Fernet key length is fixed by the spec)"
                )

    if errors:
        print(
            f"❌  Schema validation failed — {len(errors)} error(s) "
            f"in {config_path}:",
            file=sys.stderr,
        )
        for i, err in enumerate(errors, 1):
            print(f"   {i}. {err}", file=sys.stderr)
        print(file=sys.stderr)
        raise ConfigError(
            f"Fix the {len(errors)} error(s) above in {config_path} and re-run."
        )

    return secrets  # type: ignore[return-value]


# ── Generators ───────────────────────────────────────────────────────────────

def gen_random_base64(length: int) -> str:
    """
    URL-safe base64 string of exactly `length` characters.

    CHANGE [3]: Replaced manual token_bytes + urlsafe_b64encode with
    secrets.token_urlsafe (stdlib). token_urlsafe(n) produces ~4n/3
    URL-safe base64 chars from n random bytes — same output, less code,
    no reimplementation of stdlib behaviour.
    """
    # Solve for byte count: token_urlsafe(n) yields ceil(4n/3) chars.
    # Request enough bytes so slicing to `length` always succeeds.
    byte_count = math.ceil(length * 3 / 4)
    return _secrets.token_urlsafe(byte_count)[:length]


def gen_random_hex(length: int) -> str:
    """
    Lowercase hexadecimal string of exactly `length` characters.

    CHANGE [2]: Fixed entropy calculation. The previous implementation
    called token_hex(length) which returns 2*length hex chars, then
    sliced to `length` — consuming 2× the entropy silently.

    Correct contract: `length` = number of output hex characters.
    Entropy = length/2 bytes (ceiling). E.g. length=16 → 8 bytes entropy.
    """
    byte_count = math.ceil(length / 2)
    return _secrets.token_hex(byte_count)[:length]


def gen_fernet() -> str:
    """
    32-byte URL-safe base64 Fernet key (format fixed by spec).

    CHANGE [9]: Removed silent stdlib fallback. cryptography is now a
    hard dependency installed in .venv-secrets by gen-secrets.sh.
    A missing package now fails loudly rather than producing a key that
    may silently differ from what Airflow's Fernet validator expects.
    """
    try:
        from cryptography.fernet import Fernet
    except ImportError:
        raise ConfigError(
            "The 'cryptography' package is required for method 'fernet' but is "
            "not installed.\n"
            "   If running gen_secrets.py directly, install it first:\n"
            "   pip install cryptography\n"
            "   Or use gen-secrets.sh which manages the venv automatically."
        )
    return Fernet.generate_key().decode()


def generate(entry: dict) -> str:
    """Dispatch to the correct generator and return the secret value."""
    method: str = entry["method"]
    length: int = entry.get("length", LENGTH_DEFAULT)

    if method == "static":
        return str(entry["value"])
    elif method == "random_base64":
        return gen_random_base64(length)
    elif method == "random_hex":
        return gen_random_hex(length)
    elif method == "fernet":
        return gen_fernet()
    else:
        raise ValueError(f"Unknown method: {method!r}")  # unreachable post-validate


# ── .env.local helpers ───────────────────────────────────────────────────────

def bootstrap(env_local: Path) -> None:
    """
    Create .env.local with a header comment if it does not exist.

    CHANGE [8]: File is created with mode 0600 (owner read/write only).
    Prevents world-readable secrets on multiuser machines.
    """
    if not env_local.exists():
        # touch with restrictive mode before writing any content
        env_local.touch(mode=0o600)
        env_local.write_text(ENV_LOCAL_HEADER, encoding="utf-8")
        print(f"📄  Created {env_local}  (mode 0600)")


def read_existing_keys(env_local: Path) -> set[str]:
    """Return the set of env var names already defined in .env.local."""
    if not env_local.exists():
        return set()
    keys: set[str] = set()
    for line in env_local.read_text(encoding="utf-8").splitlines():
        m = ENV_VAR_RE.match(line)
        if m:
            keys.add(m.group(1))
    return keys


def remove_keys(env_local: Path, rotate_keys: set[str]) -> int:
    """
    Strip specified keys from .env.local so they are regenerated on the
    next run. Returns the number of lines removed.

    CHANGE [5]: Rotation support. Removes targeted keys while leaving
    all other keys intact, preserving the idempotency guarantee for
    everything that isn't being rotated.
    """
    if not env_local.exists() or not rotate_keys:
        return 0

    lines = env_local.read_text(encoding="utf-8").splitlines(keepends=True)
    kept = []
    removed_count = 0

    for line in lines:
        m = ENV_VAR_RE.match(line)
        if m and m.group(1) in rotate_keys:
            removed_count += 1
        else:
            kept.append(line)

    env_local.write_text("".join(kept), encoding="utf-8")
    return removed_count


def append_secrets(env_local: Path, new_secrets: list[tuple[str, str]]) -> None:
    """
    Append all new KEY=VALUE pairs to .env.local in one write.

    CHANGE [12]: Replaced per-key open() calls with a single batched
    write. Reduces file-handle churn and makes the append atomic at
    the OS buffer level.
    """
    if not new_secrets:
        return
    payload = "".join(f"{key}={value}\n" for key, value in new_secrets)
    with env_local.open("a", encoding="utf-8") as fh:
        fh.write(payload)


def append_run_metadata(env_local: Path) -> None:
    """
    Write a timestamped metadata comment to .env.local after each run.

    CHANGE [10]: Provides an audit trail — when were secrets last
    generated/rotated and on which machine. Useful for compliance reviews
    and debugging stale-credential issues.
    """
    ts   = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds") + "Z"
    host = socket.gethostname()
    with env_local.open("a", encoding="utf-8") as fh:
        fh.write(f"\n# Last run: {ts}  host: {host}\n")


# ── CLI ──────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate secrets from config/secrets.yaml into .env.local",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  # Generate all missing secrets\n"
            "  python3 scripts/gen_secrets.py\n\n"
            "  # Rotate specific secrets (removes + regenerates)\n"
            "  python3 scripts/gen_secrets.py --rotate MINIO_ROOT_PASSWORD,AIRFLOW_SECRET_KEY\n"
        ),
    )
    parser.add_argument(
        "--config",
        default="config/secrets.yaml",
        metavar="PATH",
        help="Path to secrets.yaml (default: config/secrets.yaml)",
    )
    parser.add_argument(
        "--env-file",
        default=".env.local",
        metavar="PATH",
        dest="env_file",
        help="Path to .env.local (default: .env.local)",
    )
    # CHANGE [5]: --rotate flag for targeted key rotation.
    parser.add_argument(
        "--rotate",
        default="",
        metavar="KEY1,KEY2,...",
        help=(
            "Comma-separated list of keys to forcibly regenerate. "
            "The named keys are removed from .env.local before generation runs, "
            "so they are treated as missing and written fresh. "
            "All other keys are untouched."
        ),
    )
    return parser.parse_args()


# ── Main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    args = parse_args()

    config_path  = Path(args.config)
    env_local    = Path(args.env_file)
    rotate_keys  = {k.strip() for k in args.rotate.split(",") if k.strip()}

    # ── Load YAML ─────────────────────────────────────────────────────────────
    if not config_path.exists():
        raise ConfigError(
            f"Secrets config not found: {config_path}\n"
            f"   Expected at: {config_path.resolve()}"
        )

    with config_path.open(encoding="utf-8") as fh:
        try:
            config = yaml.safe_load(fh)
        except yaml.YAMLError as exc:
            raise ConfigError(f"Failed to parse {config_path}:\n   {exc}")

    # ── Validate ──────────────────────────────────────────────────────────────
    secret_defs = validate(config, str(config_path))

    # ── Bootstrap .env.local ──────────────────────────────────────────────────
    bootstrap(env_local)

    # ── Rotation: strip targeted keys so they are treated as missing ──────────
    # CHANGE [5]: Rotation removes keys before the existence check so the
    # standard "skip if present" logic regenerates them naturally.
    if rotate_keys:
        # Validate that every requested rotation key exists in the config.
        defined_keys = {e["key"] for e in secret_defs}
        unknown_rotate = rotate_keys - defined_keys
        if unknown_rotate:
            raise ConfigError(
                f"--rotate contains key(s) not defined in {config_path}: "
                f"{', '.join(sorted(unknown_rotate))}"
            )
        removed = remove_keys(env_local, rotate_keys)
        print(
            f"♻️   Rotation: removed {removed} key(s) from {env_local} "
            f"({', '.join(sorted(rotate_keys))})"
        )

    # ── Generate missing secrets ──────────────────────────────────────────────
    existing = read_existing_keys(env_local)

    print(
        f"🔐  Checking secrets in {env_local}  "
        f"(config: {config_path})..."
    )

    # CHANGE [12]: Collect all new secrets first, then write in one batch.
    to_write:  list[tuple[str, str]] = []
    skipped:   list[str]             = []

    for entry in secret_defs:
        key: str = entry["key"]

        if key in existing:
            skipped.append(key)
            continue

        value = generate(entry)
        to_write.append((key, value))
        print(f"   ✔  {key:<35}  [{entry['method']}]")

    append_secrets(env_local, to_write)

    # CHANGE [10]: Always write a run-metadata comment so the file records
    # when it was last touched, regardless of whether new secrets were added.
    append_run_metadata(env_local)

    # ── Summary ───────────────────────────────────────────────────────────────
    if to_write:
        print(f"✅  {len(to_write)} secret(s) written to {env_local}")
        if skipped:
            print(
                f"⏭️   {len(skipped)} already present — skipped "
                f"({', '.join(skipped)})"
            )
        print(f"   Review:  cat {env_local}")
    else:
        print(
            f"✅  All {len(skipped)} secret(s) already present in "
            f"{env_local} — nothing changed."
        )


if __name__ == "__main__":
    main()